---
after_success:
- cover -report coveralls
install:
- export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c
  HARNESS_TIMER=1
- cpanm --quiet --notest Devel::Cover::Report::Coveralls
language: perl
perl:
- '5.18'
- '5.16'
- '5.14'
- '5.12'
- '5.10'
- '5.8'
script:
- PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove
  -lrsv t
- cover
